- hosts: all
  gather_facts: no
  vars:
    chroot_exec: arch-chroot /mnt
  tasks:
    - name: Configure localtime
      command: "{{ chroot_exec }} ln -sf /usr/share/zoneinfo/US/Michigan /etc/localtime"
    - name: Configure locale
      command: "{{ chroot_exec }} sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen"
    - name: Generate locales
      command: "{{ chroot_exec }} locale-gen"
    - name: Configure locale.conf
      shell: "{{ chroot_exec }} echo 'LANG=en_US.UTF-8' > /etc/locale.conf"
    - name: Configure hostname
      command: "{{ chroot_exec }} echo 'host01' > /etc/hostname"
    - name: Configure /etc/hosts
      shell: "{{ chroot_exec }} printf '127.0.0.1	localhost\n::1		localhost\n127.0.1.1	host01.localdomain	host01\n' >> /etc/hosts"
    - name: Set initial root password
      shell: "{{ chroot_exec }} echo 'root:thisISaSECUREpassword12' | chpasswd"
    - name: Enable SSH as root
      command: "{{ chroot_exec }} sed -i 's/#PermitRootLogin .*$/PermitRootLogin yes/g' /etc/ssh/sshd_config"
    - name: Enable sshd
      command: "{{ chroot_exec }} systemctl enable sshd"
    - name: Install Grub bootloader
      command: "{{ chroot_exec }} grub-install /dev/sda"
    - name: Generate grub configuration
      command: "{{ chroot_exec }} grub-mkconfig -o /boot/grub/grub.cfg"
    - name: Unmount /mnt
      command: umount /mnt
    - name: Sync changes
      command: sync
